const experiences = [
  {
    title: "AI Policy Engineer",
    company: "Independent Consultant",
    type: "Self-employed",
    period: "Oct 2023 – Present",
    location: "Philadelphia, PA",
    highlights: [
      "Designed and deployed FERPA and Title IX compliance dashboards for public school districts, automating policy tracking and audit readiness",
      "Founded and scaled an AI consultancy delivering rapid automation prototypes for small and mid-sized organizations",
      "Led three proof-of-concept initiatives translating regulatory and policy frameworks into enforceable technical controls",
      "Built GPT-5 and Claude-based tools to extract, normalize, and structure regulatory requirements from unstructured policy documents",
      "Conducted five NIST AI Risk Management Framework (RMF) feasibility assessments, producing risk registers and mitigation roadmaps",
      "Integrated open-source LLMs (LLaMA, Mistral) into client workflows, reducing infrastructure and inference costs by approximately 40%",
    ],
  },
  {
    title: "Penetration Tester",
    company: "Defense Intelligence Agency & Lockheed Martin",
    type: "Contract",
    period: "Nov 2024 – May 2025",
    location: "Washington, DC (Remote)",
    highlights: [
      "Executed more than 12 authorized penetration tests across classified and unclassified environments using Metasploit, Burp Suite, and Nmap",
      "Identified 47 critical and high-severity vulnerabilities and delivered remediation plans within a 48-hour SLA",
      "Reduced reported security incidents by 30% through proactive OSINT reconnaissance and threat modeling",
      "Briefed senior government and contractor stakeholders with risk-prioritized findings and actionable remediation strategies",
    ],
  },
  {
    title: "Management Consulting Analyst",
    company: "Accenture Federal Services",
    type: "Full-time",
    period: "Jul 2021 – Oct 2024",
    location: "Washington, DC",
    highlights: [
      "Optimized Department of Defense capital project portfolios, improving resource utilization by approximately 30%",
      "Developed compliance and governance frameworks supporting Defense Logistics Agency modernization initiatives",
      "Led UX/UI design and content strategy for a Department of Energy public-facing website",
      "Delivered quantitative analyses that contributed to a 15% reduction in operational costs across client programs",
    ],
  },
  {
    title: "Business Analyst",
    company: "SAS, SAP SuccessFactors",
    type: "Full-time",
    period: "Dec 2019 – Mar 2021",
    location: "Newtown Square, PA",
    highlights: [
      "Produced ROI and cost-benefit analyses to inform executive budgeting and investment decisions",
      "Improved operational efficiency by 25% through process analysis and data-driven recommendations",
      "Streamlined reporting workflows, reducing data retrieval time by approximately 30%",
    ],
  },
];
